services:
  simple-login-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-login-nodejs-api
    container_name: simple-login-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/docker/api-simple-login/app/src
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - dev_login_api_db_network

networks:
  dev_login_api_db_network:
    external: true