services:
  simple-login-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-login-nodejs-api
    container_name: simple-login-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/docker/restful-api-nodejs/app/src
    restart: unless-stopped